### ISSUE TITLE
[FEATURE REQUEST] - <title> AndroidTV??

### ISSUE THREAD

**Issue by MarshMeadow** [Chouten-App/Chouten-Android#38]
### Describe your suggested feature

can or is there an android tv version??

### Examples

like the other good tv apps??

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **latest version**.

**Comment by Adolar0042** [comment]
Hi, thanks for your interest in Chouten. Currently we don't plan on making a tv version of the app due to various factors.

**Comment by aicynide** [comment]
Step 1: Open Android Studio
Step 2: Open Emulator in Android Studio
Step 3: Android TV 4k Ultra emulator
Step 4: Test your apk for ChoutenTV there
